//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team3ADProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class adjustment
    {
        public int adjustment_id { get; set; }
        public System.DateTime adjustment_date { get; set; }
        public int employee_id { get; set; }
        public string item_number { get; set; }
        public int adjustment_quantity { get; set; }
        public double adjustment_price { get; set; }
        public string adjustment_status { get; set; }
        public string employee_remark { get; set; }
        public string manager_remark { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual inventory inventory { get; set; }
    }
}
