//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team3ADProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class budget
    {
        public string department_id { get; set; }
        public int year { get; set; }
        public string month { get; set; }
        public Nullable<int> budget1 { get; set; }
        public Nullable<int> spent { get; set; }
    
        public virtual department department { get; set; }
    }
}
