//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team3ADProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class department_rep
    {
        public int appointment_id { get; set; }
        public string department_id { get; set; }
        public int representative_id { get; set; }
        public System.DateTime appointed_date { get; set; }
        public string representative_status { get; set; }
    
        public virtual department department { get; set; }
        public virtual employee employee { get; set; }
    }
}
