//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team3ADProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisition_order_detail
    {
        public string requisition_id { get; set; }
        public string item_number { get; set; }
        public int item_requisition_quantity { get; set; }
        public int item_distributed_quantity { get; set; }
        public int item_pending_quantity { get; set; }
        public double item_requisition_price { get; set; }
    
        public virtual inventory inventory { get; set; }
        public virtual requisition_order requisition_order { get; set; }
    }
}
