//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team3ADProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier()
        {
            this.purchase_order = new HashSet<purchase_order>();
            this.supplier_itemdetail = new HashSet<supplier_itemdetail>();
        }
    
        public string supplier_id { get; set; }
        public string supplier_name { get; set; }
        public string supplier_status { get; set; }
        public string supplier_email { get; set; }
        public string contact_name { get; set; }
        public int phone_number { get; set; }
        public int fax_number { get; set; }
        public string GST_registration { get; set; }
        public string address { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchase_order> purchase_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier_itemdetail> supplier_itemdetail { get; set; }
    }
}
